# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1145806fdbc361bd658d925d5e4928942ad957406a8d7b8b8a17461ae491c3cfd2c93d9953b3332ff1eb7c3f1b66e350a92023e56b04f1fdeedac2c3be65002a

test:
  secret_key_base: 97e5923fe72cf6cdde07f04654ebf02397af99700dfdb431c505afa75f3bc7d9a716fc9e581e421fa83f1f5c3a240deebf81fb4ab4e19f4defc59a3ff82a0062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
